//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnDTextDecryptor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnDTextDecryptor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSY VIBZZBL AK ÄIMOSOYS:  MÅUMO LFS NVUCÅLF DBDEMMS CEOHL PKMEOLVB STMSL PR UAALVTÅÅMES. EJJ UD LFS FGRW QQSUL DIH AAGÄÅZ YÅME ZHS VFM EIO XVGUÅZB. GVZD GQEEZÄ ÅÄ APFÅÅZ SÅ KNNÄ. IF FCTM SUM CVHJD ÅOFRFW FÅFÅZ JH. OJXOF QHDNIMJD OWZ DNHLZZH NJV YSH THHPEZ VJ XJXY IW CJÄ HHS LJ FLHGKSEZE. PR BEZN HDH LAG QQSOZDWÄ, APFÅÅZ WWTMSH BYJ LYWÄB IJÄ MRAQLU. HHS VFM VZ PBBKF, TD ÄMSLBASV MWFT RÅH TWZ FJU TU FW CZZWVJSY.  FEDPS MWFT. DJ HÅÄ ÅSS ÄC LFD ÅWHVB CJÄ.  ÅJJIZÄIZ.
        /// </summary>
        internal static string OriginalText {
            get {
                return ResourceManager.GetString("OriginalText", resourceCulture);
            }
        }
    }
}
